server {
  listen 80;
  client_max_body_size 10m;

  # 静的ファイルが置いてある場所
  root /public;

  location / {
    # 1. まず $uri (ファイルそのもの) を探す
    # 2. なければ @php ブロックへ飛ばす
    try_files $uri @php;
  }

  location @php {
    # PHPコンテナの9000番ポートへ
    fastcgi_pass app:9000;
    include fastcgi_params;
    # PHPコンテナ内での index.php の絶対パスを指定
    fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
  }

  # 直打ちで .php にアクセスされた場合も対応
  location ~ \.php$ {
    fastcgi_pass app:9000;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
  }
}